services:
  - type: web
    name: render-spring-demo
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/render-spring-demo-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
