server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://ep-floral-meadow-ao9kjp0d-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_dJFZgzsnT5w4&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
